feat(chrome): add chrome component
zendeskgarden/website pull request #168
Opened 2020-09-02 17:35 UTC by rossmoody

## Description

This PR adds the Chrome component documentation and examples to the website. 

## Detail

## Checklist

- [ ] :ok_hand: website updates are Garden Designer approved (add the designer as a reviewer)
- [ ] :black_nib: copy updates are approved (add the content strategist as a reviewer)
- [ ] :link: considered opportunities for adding cross-reference URLs (grep for keywords)
- [ ] :wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver
- [ ] :zap: audited via [web.dev](https://web.dev/measure/) for performance and SEO
- [ ] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11

2020-09-02 17:36 UTC, rossmoody commented
@jzempel I noticed that here and on the legacy site, the Sidebar component has a tendency to appear in the `start` position regardless of where it's placed in the DOM. Is this intentional?

2020-09-03 23:23 UTC, jzempel commented
@rossmoody are you referring to the `<Nav>` component? Yes, it receives a flex `order` of -1, ensuring that (compared to the other Chrome components) tab order is consistent from one product to the next – always moves down the side `<Nav>`, then to the top `<Header>`. For good accessibility, the DOM structure should always mimic this order. But we belt-n-suspenders this thing just in case someone decides to go rogue with the implementation.

2020-09-04 00:22 UTC, rossmoody commented
@jzempel I was referring to the `Sidebar` component that sits inside `Content`. It seemed like it was always positioning to the left of `<Main>` but from design mocks I was expecting it to be on the right.

2020-09-04 00:57 UTC, jzempel requested changes

2020-09-04 00:57 UTC, jzempel commented on package.json
> +    "@zendeskgarden/react-chrome": "8.19.0",
Can this be set to `8.21.1` so that when it's merged with #165, all things are same-same?

2020-09-04 00:57 UTC, jzempel commented on src/examples/chrome/ChromeDefault.tsx
> +    <Col>
The `Row-Col` container is not needed here.

2020-09-04 00:57 UTC, jzempel commented on src/examples/chrome/ChromeDefault.tsx
> +      <Chrome isFluid style={{ height: 500 }}>
Also specify a `min-width` style (600?) to prevent the layout from squishing on mobile.

2020-09-04 00:57 UTC, jzempel commented on src/examples/chrome/ChromeDefault.tsx
> +              <ProductIcon />
Can we remove `product="support"` and use `garden.svg` for the product icon like:

`<ProductIcon style={{ color: PALETTE.green[400] }} />`

I'd prefer to stay product-agnostic here, if possible.

2020-09-04 00:57 UTC, jzempel commented on src/examples/chrome/ChromeNavigation.tsx
> +      <Col>
Row-Col can be removed.

2020-09-04 00:57 UTC, jzempel commented on src/examples/chrome/ChromeDefault.tsx
> +            <NavItemText>Zendesk Support</NavItemText>
"Zendesk Garden"

2020-09-04 00:57 UTC, jzempel commented on src/examples/chrome/ChromeNavigation.tsx
> +              <NavItemText>Zendesk Support</NavItemText>
Same ProductIcon and "Zendesk Garden" suggestion as above.

2020-09-04 00:57 UTC, jzempel commented on src/examples/chrome/ChromeNavigation.tsx
> +  const [subNav, setSubNav] = useState('item-1');
Might be good to add this same state management to the default example.

2020-09-04 00:57 UTC, jzempel commented on src/examples/chrome/ChromeNavigation.tsx
> +          <Body>
A `<Header />` component must be added – even if empty. Without it, we get the unexpected space showing beneath the content in this example.

2020-09-04 00:57 UTC, jzempel commented on src/examples/chrome/ChromeStandaloneHeader.tsx
> +    <Col>
Row-Col not needed.

2020-09-04 00:57 UTC, jzempel commented on src/examples/chrome/ChromeStandaloneHeader.tsx
> +              <HeaderItemText>Zendesk Support</HeaderItemText>
Recommend swapping out for "Garden"

2020-09-04 01:02 UTC, jzempel commented
@rossmoody `Sidebar` is, indeed, always on the left. Some day a `Drawer` (naming tbd) will be on the right. See Support or Guide Admin products for details.

2020-09-04 19:23 UTC, jzempel approved these changes

2020-09-04 19:34 UTC, merged