James.sann/component status indicator
zendeskgarden/website pull request #426
Opened 2022-09-29 06:17 UTC by james-sann

## Checklist

- [ ] :link: considered opportunities for adding cross-reference URLs (grep for keywords)
- [ ] :wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver
- [ ] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11

2022-09-29 15:00 UTC, jzempel requested changes
This is coming along nicely, @james-sann

2022-09-29 15:00 UTC, jzempel commented on src/pages/components/status-indicator.mdx
> +      <li>To display contextual information for a users current status</li>
```suggestion
      <li>To display contextual information for a user's current status</li>
```

2022-09-29 15:00 UTC, jzempel commented on src/pages/components/status-indicator.mdx
> +  The Status indicator provides a consistent, accessible representation of a users current
```suggestion
  The Status indicator provides a consistent, accessible representation of a user's current 
```

2022-09-29 15:00 UTC, jzempel commented on src/pages/components/status-indicator.mdx
> +### Status indicator
```suggestion
### StatusIndicator
```

This needs to match the code component name.

2022-09-29 15:00 UTC, jzempel commented on src/pages/components/status-indicator.mdx
> +<Component components={props.data.mdx.components} componentName="statusIndicator" />
```suggestion
<Component components={props.data.mdx.components} componentName="statusIndicator" />

Provide an `aria-label` to ensure it is accessible.
```

2022-09-29 15:33 UTC, jzempel commented on src/pages/components/status-indicator.mdx
> +<Component components={props.data.mdx.components} componentName="statusIndicator" />
fwiw https://github.com/zendeskgarden/react-components/pull/1413 will eventually fix the missing `<Component>` extends clause – which should always be at the top.

2022-09-30 04:56 UTC, james-sann commented on src/examples/avatar/StatusIndicatorType.tsx
> +const Example = () => (
Thanks @jzempel! I made an attempt that seems to work. Feel free to re-adjust if it needs tweaking.

2022-09-30 04:56 UTC, james-sann commented
@jzempel All changes have been made.

2022-09-30 14:23 UTC, jzempel commented on src/examples/avatar/StatusIndicatorType.tsx
> +const Example = () => (
Perfect.

2022-09-30 14:24 UTC, jzempel approved these changes

2022-09-30 14:25 UTC, merged