chore: expands menu and combobox JSX API documentation
zendeskgarden/website pull request #606
Opened 2024-08-02 17:42 UTC by geotrev

## Description

Adds new sections to Menu and Combobox API docs about JSX requirements to help address repeated pitfalls in component composition.

## Checklist

- ~~:ok_hand: website updates are Garden Designer approved (add the designer as a reviewer)~~
- [ ] :black_nib: copy updates are approved (add the content strategist as a reviewer)
- ~~:link: considered opportunities for adding cross-reference URLs (grep for keywords)~~
- ~~:wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver~~
- ~~:memo: tested in Chrome, Firefox, Safari, Edge~~

2024-08-02 19:33 UTC, ze-flo reviewed
Should we mention that Menu will only recognizes sub component with the same prop signature as `Item` and `ItemGroup`?

2024-08-02 20:11 UTC, geotrev commented
> Should we mention that Menu will only recognizes sub component with the same prop signature as `Item` and `ItemGroup`?

I wondered about that too. Yeah, feels like it might be worth it since it happens so often in consumer code.

2024-08-02 21:19 UTC, ze-flo approved these changes
Welcomed additions to our docs. Great job! 💯

2024-08-02 21:19 UTC, ze-flo commented on src/pages/components/menu.mdx
> +
❤️

2024-08-06 15:19 UTC, jzempel requested changes

2024-08-06 15:19 UTC, jzempel commented on src/pages/components/combobox.mdx
> +When authoring a `Combobox`, prefer either a vanilla function and/or `Array.map` to generate options:
Re-write to simplify and use [active voice](https://garden.zendesk.com/content/principles#use-the-active-voice). Something like:

```
Use `Array.map` to iterate over options.
```

Tools like https://hemingwayapp.com/ can help.

2024-08-06 15:19 UTC, jzempel commented on src/pages/components/combobox.mdx
> +If wrapping subcomponents `OptGroup` or `Option`, ensure the prop signature matches the contained components:
ditto

2024-08-06 15:19 UTC, jzempel commented on src/pages/components/menu.mdx
> +When authoring a `Menu`, prefer either a vanilla function and/or `Array.map` to generate items:
ditto

2024-08-06 15:19 UTC, jzempel commented on src/pages/components/menu.mdx
> +If wrapping subcomponents `ItemGroup` or `Item`, ensure the prop signature matches the contained components:
ditto

2024-08-06 17:24 UTC, geotrev commented
I realized we don't necessarily use code styling when referencing a component name. Should I remove the ticks from the new text?

Compare "Menu" in the description here:

<img width="688" alt="Screenshot 2024-08-06 at 12 22 46 PM" src="https://github.com/user-attachments/assets/7406997a-5f4b-461a-8cdf-2cb70edaae01">

With the new text in this PR:

<img width="777" alt="Screenshot 2024-08-06 at 12 23 38 PM" src="https://github.com/user-attachments/assets/1b90fbd5-04a0-41b4-a8ea-6b8b624d7988">

2024-08-07 14:14 UTC, jzempel commented on src/pages/components/combobox.mdx
> +)
Should the canonical example be using `forwardRef`?

2024-08-07 14:18 UTC, jzempel commented
> I realized we don't necessarily use inline code styling when referencing a component name. Should I remove the ticks from the new text?
> 
> Compare "Menu" in the description here:
> 
> <img alt="Screenshot 2024-08-06 at 12 22 46 PM" width="688" src="https://private-user-images.githubusercontent.com/3946669/355544101-7406997a-5f4b-461a-8cdf-2cb70edaae01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDAzOTIsIm5iZiI6MTcyMzA0MDA5MiwicGF0aCI6Ii8zOTQ2NjY5LzM1NTU0NDEwMS03NDA2OTk3YS01ZjRiLTQ2MWEtOGNkZi0yY2I3MGVkYWFlMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMTQxNDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY1OGM1NDY3ODFkMzY3YTllNzRiMDUwOGY4NzEyMTFhZWZhZmExMmIxNDcyYmI0NDI4ODNlZTRjYTY0ZDFhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qYDP9W9czBDfNqkUghSHYPOA2rVthGKPKfi5T-zJzwU">
> With the new text in this PR:
> 
> <img alt="Screenshot 2024-08-06 at 12 23 38 PM" width="777" src="https://private-user-images.githubusercontent.com/3946669/355544176-1b90fbd5-04a0-41b4-a8ea-6b8b624d7988.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDAzOTIsIm5iZiI6MTcyMzA0MDA5MiwicGF0aCI6Ii8zOTQ2NjY5LzM1NTU0NDE3Ni0xYjkwZmJkNS0wNGEwLTQxYjQtYThlYS02YjhiNjI0ZDc5ODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMTQxNDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjM5YmRmYjU0YmQ2ZmQxNGJjOGQ1N2Q5NGI0YzM4OTc5N2FiMTE5YjM0MjU2YjcwY2RiNTU5ODY4NmI3ZDY0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sBGr6Aah8pq423HIvAZ4KE0vu84B9p70TLtwwhVdjDo">

Within the context of the API section, the code naming and treatment makes sense.

2024-08-07 20:06 UTC, jzempel commented on src/pages/components/menu.mdx
> +)
Should `forwardRef` be shown here, too?

2024-08-12 12:50 UTC, jzempel approved these changes

2024-08-12 16:06 UTC, geotrev commented on src/pages/components/menu.mdx
> +)
Thanks for catching this. :D

2024-08-12 16:06 UTC, merged