chore: remove `react-dropdowns.legacy`
zendeskgarden/website pull request #611
Opened 2024-08-05 21:10 UTC by ze-flo

## Description

Removes `react-dropdowns.legacy`

## Checklist

- [ ] ~~:ok_hand: website updates are Garden Designer approved (add the designer as a reviewer)~~
- [ ] ~~:black_nib: copy updates are approved (add the content strategist as a reviewer)~~
- [ ] ~~:link: considered opportunities for adding cross-reference URLs (grep for keywords)~~
- [ ] ~~:wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver~~
- [ ] ~~:memo: tested in Chrome, Firefox, Safari, Edge~~

2024-08-05 21:14 UTC, ze-flo commented
Reposting this [comment](https://github.com/zendeskgarden/website/pull/610#issuecomment-2269876949):

> Should we update the [migration guide](https://github.com/zendeskgarden/react-components/blob/1c9eabbb12b41b420410c23f1b925b20202ba6d4/docs/migration.md?plain=1#L116) to let our users know that while we're still publishing react-dropdown.legacy for compatibility purposes, its documentation will only be available in the V8 version of the website?

2024-08-06 16:42 UTC, geotrev commented
> Reposting this [comment](https://github.com/zendeskgarden/website/pull/610#issuecomment-2269876949):
> 
> > Should we update the [migration guide](https://github.com/zendeskgarden/react-components/blob/1c9eabbb12b41b420410c23f1b925b20202ba6d4/docs/migration.md?plain=1#L116) to let our users know that while we're still publishing react-dropdown.legacy for compatibility purposes, its documentation will only be available in the V8 version of the website?

I think that's a reasonable think to do.

2024-08-06 16:43 UTC, geotrev commented on src/examples/menu/Nested.tsx
> -import { Separator } from '@zendeskgarden/react-dropdowns';
This must have been a weird mistake in the v8 docs. good catch.

2024-08-06 16:46 UTC, geotrev commented on src/examples/tooltip/TooltipPlacement.tsx
> +const PLACEMENTS: Record<string, ITooltipProps['placement']> = {
I have this covered in #612 as well, but if yours merges first then I'll just rebase and it'll resolve automatically. :)

2024-08-06 16:50 UTC, geotrev requested changes
I want to say `src/fragments` can go (along with the `gatsby-config.ts` entry for that directory). Just double checking you saw that? 🙂

2024-08-06 19:42 UTC, geotrev approved these changes

2024-08-06 19:48 UTC, merged

2024-08-06 20:13 UTC, jzempel commented
> Reposting this [comment](https://github.com/zendeskgarden/website/pull/610#issuecomment-2269876949):
> 
> > Should we update the [migration guide](https://github.com/zendeskgarden/react-components/blob/1c9eabbb12b41b420410c23f1b925b20202ba6d4/docs/migration.md?plain=1#L116) to let our users know that while we're still publishing react-dropdown.legacy for compatibility purposes, its documentation will only be available in the V8 version of the website?

The migration guide already spells out the existence of `dropdowns.legacy` and we won't have a final version 8 link artifact to the website until after v9 ships. I think we're good for now. If this becomes a repeat concern in the future, let's think about how to address it then (i.e. updating the in-place migration guide, etc)