fix(components): add subcomponent property syntax to Tooltip configuration
zendeskgarden/website pull request #613
Opened 2024-08-06 20:57 UTC by geotrev

Forgot this in #612 😶 

<img width="867" alt="Screenshot 2024-08-06 at 3 56 23 PM" src="https://github.com/user-attachments/assets/b9a7952b-7d22-40f9-a23c-385b1e5902de">

<img width="413" alt="Screenshot 2024-08-06 at 3 56 38 PM" src="https://github.com/user-attachments/assets/d81ac13c-08a9-4c08-9937-49699f5dc5d6">

2024-08-06 21:00 UTC, ze-flo approved these changes
Good catch!

2024-08-06 21:06 UTC, jzempel requested changes

2024-08-06 21:06 UTC, jzempel commented on src/pages/components/tooltip.mdx
> +### Tooltip.Paragraph
```suggestion
#### Tooltip.Paragraph
```

Subcomponents are H4

2024-08-06 21:06 UTC, jzempel commented on src/pages/components/tooltip.mdx
> +### Tooltip.Title
```suggestion
#### Tooltip.Title
```

2024-08-07 12:52 UTC, jzempel approved these changes

2024-08-12 21:14 UTC, geotrev commented
Waiting for `displayName` changes from `next.21` so the subcomponent values are correct.

2024-08-13 00:07 UTC, ze-flo commented
> Waiting for `displayName` changes from `next.21` so the subcomponent values are correct.

Handled in https://github.com/zendeskgarden/website/pull/621

2024-08-13 00:09 UTC, ze-flo commented
This PR might be redundant once https://github.com/zendeskgarden/website/pull/621 merges.

2024-08-14 15:54 UTC, geotrev commented
Closing given the updates pushed in #621

2024-08-14 15:54 UTC, closed without merging